name: Build Test

on:
  push:
    branches: [ "main", "3.0.x"]
  pull_request:
    branches: [ "main", "3.0.x" ]

permissions:
  contents: read

jobs:
  building:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Tag
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout tools repository (sibling ../tools)
        uses: actions/checkout@v3
        with:
          repository: WaterMediaTeam/tools
          path: ../tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout binaries repository (sibling ../binaries)
        uses: actions/checkout@v3
        with:
          repository: WaterMediaTeam/binaries
          path: ../binaries
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK (21)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Set up Gradle 9.0.0
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '9.0.0'

      - name: Show Gradle & Java versions
        run: |
          gradle --version
          java -version

      - name: Build
        run: gradle build